homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080

advanced:
  log_level: info
  log_namespaced_levels:
    z2m:mqtt: warning
  timestamp_format: 'YYYY-MM-DD HH:mm:ss'
  log_output:
    - console
